version: '3.4'

services:
  jupyter:
    image: aot29/r-notebook
    restart: 'no'
    ports:
      - "8888:8888"
    volumes:
      - ".:/home/jovyan"

    command:
      "jupyter lab --ip='*' --NotebookApp.token='' --NotebookApp.password=''"
